//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SolverGUI_0._1.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SolverGUI_0._1.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;kotus-sanalista&gt;
        ///&lt;st&gt;&lt;s&gt;aakkonen&lt;/s&gt;&lt;t&gt;&lt;tn&gt;38&lt;/tn&gt;&lt;/t&gt;&lt;/st&gt;
        ///&lt;st&gt;&lt;s&gt;aakkosellinen&lt;/s&gt;&lt;t&gt;&lt;tn&gt;38&lt;/tn&gt;&lt;/t&gt;&lt;/st&gt;
        ///&lt;st&gt;&lt;s&gt;aakkosellisesti&lt;/s&gt;&lt;t&gt;&lt;tn&gt;99&lt;/tn&gt;&lt;/t&gt;&lt;/st&gt;
        ///&lt;st&gt;&lt;s&gt;aakkosellisuus&lt;/s&gt;&lt;t&gt;&lt;tn&gt;40&lt;/tn&gt;&lt;/t&gt;&lt;/st&gt;
        ///&lt;st&gt;&lt;s&gt;aakkosittain&lt;/s&gt;&lt;t&gt;&lt;tn&gt;99&lt;/tn&gt;&lt;/t&gt;&lt;/st&gt;
        ///&lt;st&gt;&lt;s&gt;aakkosjärjestys&lt;/s&gt;&lt;/st&gt;
        ///&lt;st&gt;&lt;s&gt;aakkosnumeerinen&lt;/s&gt;&lt;/st&gt;
        ///&lt;st&gt;&lt;s&gt;aakkostaa&lt;/s&gt;&lt;t&gt;&lt;tn&gt;53&lt;/tn&gt;&lt;/t&gt;&lt;/st&gt;
        ///&lt;st&gt;&lt;s&gt;aakkosto&lt;/s&gt;&lt;t&gt;&lt;tn&gt;2&lt;/tn&gt;&lt;/t&gt;&lt;/st&gt;
        ///&lt;st&gt;&lt;s&gt;aakkostus&lt;/s&gt;&lt;t&gt;&lt;tn&gt;39&lt;/tn&gt;&lt;/t&gt;&lt;/st&gt;
        ///&lt;st&gt;&lt;s&gt;aalloittain&lt;/s&gt;&lt;t&gt;&lt;tn&gt;99&lt;/tn&gt;&lt;/t&gt;&lt;/st&gt;
        ///&lt;st&gt; [rest of string ....
        /// </summary>
        internal static string sanalista {
            get {
                return ResourceManager.GetString("sanalista", resourceCulture);
            }
        }
    }
}
